name: "web_app"
mode: "dev"
port: 8081
start_time: "2024-03-01"
machineID: 1
host: 127.0.0.1

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "1050"
  dbname: "godb"
  max_open_conns: 50
  max_idle_conns: 50

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  pool_size: 50
  db: 0

